### ISSUE TITLE
error issue? need suggestion, why?

### ISSUE THREAD

**Issue by prashant567-oss** [Codecademy/learn-cpp#25]
![Screenshot (118)](https://user-images.githubusercontent.com/68491950/88208296-01888c80-cc1f-11ea-97a9-eb1268052b3b.png)
still showing the error ,any idea why?

**Comment by josephdrane** [comment]
Line 9 shows `vowel.size()` and it should be `vowels.size()`

**Comment by sakshambhatia2405** [comment]
> Line 9 shows `vowel.size()` and it should be `vowels.size()`

Right
