### ISSUE TITLE
Can't figure out this step!

### ISSUE THREAD

**Issue by Ikodiko** [Codecademy/learn-cpp#29]
Im understanding the code well but, in this specific step :  if (input[ i ] == vowels[ j ])
supose that input[ i ]  = 5  in the loop for, and it is the vowel 'e' but in vowels[ j ] is like 4 index representing in 'aeiou'  the vowel 'u'
i mean the input is a vowel but is replaced by the vowel U, how to change this ? how i compare a single char to a whole vector (not one at a time)?

sorry im just learning c++.

**Comment by AnOnYmOus001100** [comment]
Specify which code or program name and module name or share a screenshot. Example: program: program1.cpp, module: Variables
