### ISSUE TITLE
dog_years2.cpp

### ISSUE THREAD

**Issue by Roy7997** [Codecademy/learn-cpp#47]
hii i am new at learning c++ can u explain me the following step:

why do we use "std::" before declaring string variable for dog_name;.
while we dont use that for int dog_age. 

do we have to use std:: while declaring string variable every time ?

![cpp doubt](https://user-images.githubusercontent.com/85838565/121813856-90fdba80-cc8b-11eb-9e84-5008a5551309.PNG)

**Comment by tymsai** [comment]
you can use `using namespace std;` instead of using `std::` every time
